StaffWork.Web/Controllers/DepartmentController.cs
using System.Security.Claims;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StaffWork.Api.Controllers;
using StaffWork.Core.Consts;
using StaffWork.Core.Interfaces;
using StaffWork.Core.Models;
using StaffWork.Core.Paramaters;
using StaffWork.Infrastructure.Filters;

namespace StaffWork.Web.Controllers
{
    public class DepartmentController : ApiBaseController<Department>
    {
        public readonly IServicesBase<Administration> AdministrationService;

        public DepartmentController(IServicesBase<Department> servicesBase, IMapper mapper, IServicesBase<Administration> administrationService)
            : base(servicesBase, mapper)
        {
            AdministrationService = administrationService;
        }
        private string GetAuthenticatedUser()
        {
            var userUidClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            return userUidClaim?.Value!;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await BussinesService.GetAllAsync(null!, ["Administration", "DepartmentAdmin.Admin"]);
            var viewModel = _mapper.Map<IEnumerable<DepartmentViewModel>>(model);

            var model1 = new Tuple<IEnumerable<DepartmentViewModel>, DepartmentFormViewModel>(
                            viewModel, await PopulateViewModelAsync());

            return View(model1);
        }
        [HttpPost]
        public async Task<IActionResult> Create(DepartmentFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var Department = _mapper.Map<Department>(viewModel);
            await BussinesService.InsertAsync(Department);
            return RedirectToAction(nameof(Index), _mapper.Map<DepartmentViewModel>(Department));
        }
        [HttpGet]
        [AjaxOnly]
        public async Task<IActionResult> EditAsync(int id)
        {
            var Department = await BussinesService.GetAsync(d => d.Id == id);
            if (Department == null)
                return NotFound();
            var viewModel = _mapper.Map<DepartmentFormViewModel>(Department);
            return PartialView("_FormEdit", await PopulateViewModelAsync(viewModel));
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> PostEditAsync(DepartmentFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var department = await BussinesService.GetAsync(d => d.Id == viewModel.Id);
            if (department == null)
                return NotFound();
            _mapper.Map(viewModel, department);

            await BussinesService.UpdateAsync(department.Id, department);
            return RedirectToAction(nameof(Index), _mapper.Map<DepartmentViewModel>(department));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var Department = await BussinesService.GetAsync(d => d.Id == id);
            if (Department == null)
                return NotFound();
            try
            {
                await BussinesService.DeleteAsync(id);
            }
            catch (Exception)
            {
                throw;
            }
            return Ok();
        }
        public async Task<IActionResult> AllowItem(DepartmentViewModel model)
        {
            var Department = await BussinesService.GetAsync(d => d.Name == model.Name);

            var isAllowed = Department is null || Department.Id.Equals(model.Id);

            return Json(isAllowed);
        }

        private async Task<DepartmentFormViewModel> PopulateViewModelAsync(DepartmentFormViewModel? model = null)
        {
            var userId = GetAuthenticatedUser();
            DepartmentFormViewModel viewModel = model is null ? new DepartmentFormViewModel() : model;

            IEnumerable<Administration> administrations;
            if (User.IsInRole(AppRoles.SuperAdmin))
                administrations = await AdministrationService.GetAllAsync();
            else
                administrations = await AdministrationService.GetAllAsync(a => a.ManagerId == userId);

            viewModel.Administrations = _mapper.Map<IEnumerable<SelectListItem>>(administrations);

            return viewModel;
        }
    }
}

StaffWork.Web/Views/Department/Index.cshtml
@model Tuple<IEnumerable<DepartmentViewModel>, DepartmentViewModel>
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery

@{
    ViewData["Title"] = "الاقسام المتاحه";
}
@section Styles
{
    <link rel="stylesheet" href="~/assets/plugins/datatables/datatables.bundle.css" />
}
<partial name="_Form" model="@Model.Item2" />
<div class="card shadow-sm">
    <partial name="_DataTablesCardHeader" />
    <div class="card-body pt-0">
        <div class="table-responsive">
            <table class="table table-row-dashed fs-2 gy-7 js-datatables" data-document-title="Departments">
                <thead>
                    <tr class="fw-bold">
                        <th style="text-align:start">القسم</th>
                        <th class="js-no-export" style="text-align:center">تعديل</th>
                        <th class="js-no-export" style="text-align:end">حذف</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var type in @Model.Item1)
                    {
                        <partial name="_DepartmentRow" model="@type" />
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />

@section Plugins
{
    <script src="~/assets/plugins/datatables/datatables.bundle.js"></script>
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

StaffWork.Web/Views/Department/_DepartmentRow.cshtml
@model DepartmentViewModel
<tr>
    <td>@Model.Name</td>
    <td style="text-align:center">
        <a href="javascript:;" class="btn btn-sm btn-outline btn-outline-dashed btn-outline-primary btn-active-light-primary js-render-modal"
           data-title="تعديل القسم" data-url="/Department/Edit/@Model.Id" data-update="true">
            تعديل القسم
        </a>
    </td>
    <td style="text-align:end">
        <a href="javascript:;" class="btn btn-sm btn-outline btn-outline-dashed btn-outline-danger btn-active-light-danger js-confirm"
           data-title="حذف القسم" data-url="/Department/Delete/@Model.Id" data-update="true" data-message="هل متأكد من حذف هذا القسم؟">
            حذف القسم
        </a>
    </td>
</tr>

StaffWork.Web/Views/Department/_Form.cshtml
@model DepartmentFormViewModel

<div class="alert bg-light-primary border border-primary border-3 border-dashed d-flex justify-content-between w-100 p-5 mb-10">
	<form method="post" asp-controller="Department" class="w-75" enctype="multipart/form-data" id="Form">
		<div class="d-flex align-items-center">
			<div class="row col-12">
				<div class="row col-6">
					<!--begin::Label-->
					<label class="col-lg-4 col-form-label required fw-semibold fs-5" asp-for="Name">أسم القسم</label>
					<!--end::Label-->
					<!--begin::Col-->
					<div class="col-lg-8">
						<!--begin::Row-->
						<div class="row mb-6">
							<!--begin::Col-->
							<div class="col-lg-12 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
								<input class="form-control form-control-solid fs-5" type="text" placeholder="ادحل أسم القسم" asp-for="Name" />
								<span asp-validation-for="Name" class="fv-plugins-message-container invalid-feedback"></span>
								<!--end::Col-->
							</div>
						</div>
						<!--end::Row-->
					</div>
					<!--end::Col-->
				</div>
				<div class="row col-6">
					<!--begin::Label-->
					<label class="mb-5 col-lg-4 col-form-label required fw-semibold fs-5">الاداره</label>
					<!--end::Label-->
					<!--begin::Col-->
					<div class="col-lg-8">
						<!--begin::Row-->
						<div class="row mb-6">
							<!--begin::Col-->
							<div class="fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
								<select aria-label="Select a Country" data-control="select2" data-placeholder="اختار الاداره..." class="form-select form-select-solid form-select-lg fw-semibold"
										asp-for="AdministrationId" asp-items="@Model.Administrations">
									<option value="">اختار الاداره...</option>
								</select>
								<span asp-validation-for="AdministrationId" class="text-danger d-block"></span>
							</div>
							<!--end::Col-->
						</div>
						<!--end::Row-->
					</div>
					<!--end::Col-->
				</div>

				<!--end::Content-->
			</div>
		</div>
	</form>
	<div class=" align-content-end">
		<button type="submit" asp-controller="Department" asp-action="Create" class="btn btn-sm btn-primary" form="Form">
			<i class="bi bi-plus-square-dotted"></i>
			اضافه
		</button>
	</div>
</div>

StaffWork.Web/Views/Department/_FormEdit.cshtml
@model DepartmentFormViewModel

<form asp-action="PostEdit"
	  data-ajax-method="post"
	  data-ajax="true"
	  data-ajax-begin="onModalBegin"
	  data-ajax-success="onModalSuccess"
	  data-ajax-failure="showErrorMessage"
	  data-ajax-complete="onModalComplete">
	@if (Model?.Id > 0)
	{
		<input type="hidden" asp-for="Id" />
	}
	<div class="row mb-6">
		<!--begin::Label-->
		<label class="col-lg-4 col-form-label required fw-semibold fs-4" asp-for="Name"></label>
		<!--end::Label-->
		<!--begin::Col-->
		<div class="col-lg-12">
			<!--begin::Row-->
			<div class="row">
				<!--begin::Col-->
				<div class="col-lg-12 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
					<input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0 fs-4" asp-for="Name">
					<span asp-validation-for="Name" class="fv-plugins-message-container invalid-feedback fs-6"></span>
				</div>
				<!--end::Col-->
			</div>
			<!--end::Row-->
		</div>
		<!--end::Col-->
	</div>
	<div class="row mb-6">
		<!--begin::Label-->
		<label class="mb-5 col-lg-4 col-form-label required fw-semibold fs-4">الاداره</label>
		<!--end::Label-->
		<!--begin::Col-->
		<div class="col-lg-12">
			<!--begin::Row-->
			<div class="row">
				<!--begin::Col-->
				<div class="fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
					<select aria-label="Select a Country" data-control="select2" data-placeholder="اختار الاداره..." class="form-select form-select-solid form-select-lg fw-semibold"
							asp-for="AdministrationId" asp-items="@Model.Administrations">
						<option value="">اختار الاداره...</option>
					</select>
					<span asp-validation-for="AdministrationId" class="text-danger d-block"></span>
				</div>
				<!--end::Col-->
			</div>
			<!--end::Row-->
		</div>
		<!--end::Col-->
	</div>
	<partial name="_ModalFooter" />
</form>