StaffWork.Web/Controllers/TaskModelController.cs
using System.Security.Claims;
using AutoMapper;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;
using StaffWork.Api.Controllers;
using StaffWork.Core.Consts;
using StaffWork.Core.Interfaces;
using StaffWork.Core.Models;
using StaffWork.Core.Paramaters;
using StaffWork.Infrastructure.Implementations;

namespace StaffWork.Web.Controllers
{
    public class TaskModelController : ApiBaseController<TaskModel>
    {
        public readonly IServicesBase<User> UserService;
        public readonly IServicesBase<TaskFile> TaskFileService;
        public readonly IServicesBase<TaskReminderFile> TaskReminderFileService;
        public readonly IServicesBase<TaskReminder> TaskReminderService;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public TaskModelController(IServicesBase<TaskModel> servicesBase, IMapper mapper, IServicesBase<User> userService, IWebHostEnvironment webHostEnvironment, IServicesBase<TaskFile> taskFileService, IServicesBase<TaskReminderFile> taskReminderFileService, IServicesBase<TaskReminder> taskReminderService) : base(servicesBase, mapper)
        {
            UserService = userService;
            _webHostEnvironment = webHostEnvironment;
            TaskFileService = taskFileService;
            TaskReminderFileService = taskReminderFileService;
            TaskReminderService = taskReminderService;
        }
        private string GetAuthenticatedUser()
        {
            var userUidClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            return userUidClaim?.Value!;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = AppRoles.Admin + "," + AppRoles.SuperAdmin)]
        public IActionResult Create()
        {
            return View("Form", PopulateViewModel());
        }
        [HttpPost]
        [Authorize(Roles = AppRoles.Admin + "," + AppRoles.SuperAdmin)]
        public async Task<IActionResult> Create(TaskModelFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var TaskModel = _mapper.Map<TaskModel>(viewModel);
            foreach (var userId in viewModel.SelectedUsers)
            {
                var user = await UserService.GetAsync(x => x.Id == userId);
                if (user != null)
                {
                    TaskModel.AssignedUsers.Add(new TaskUser
                    {
                        UserId = user.Id,
                        TaskModel = TaskModel
                    });
                }
            }
            // Handle Book images
            if (viewModel.TaskFiles != null && viewModel.TaskFiles.Count > 0)
            {
                foreach (var image in viewModel.TaskFiles)
                {
                    if (image.Length > 0)
                    {
                        var fileName = $"{Guid.NewGuid()}{Path.GetExtension(image.FileName)}";
                        var filePath = "/files/Tasks";
                        if (!Directory.Exists($"{_webHostEnvironment.WebRootPath}{filePath}"))
                            Directory.CreateDirectory($"{_webHostEnvironment.WebRootPath}{filePath}");

                        var path = Path.Combine($"{_webHostEnvironment.WebRootPath}{filePath}", fileName);

                        using var stream = System.IO.File.Create(path);
                        await image.CopyToAsync(stream);

                        var taskFile = new TaskFile
                        {
                            FileUrl = $"{filePath}/{fileName}",
                            FileName = image.FileName,
                            TaskModel = TaskModel
                        };
                        TaskModel.TaskFiles.Add(taskFile);
                    }
                }
            }
            await BussinesService.InsertAsync(TaskModel);
            return RedirectToAction("Index", _mapper.Map<TaskModelViewModel>(TaskModel));
        }
        [HttpGet]
        [Authorize(Roles = AppRoles.Admin + "," + AppRoles.SuperAdmin)]
        public async Task<IActionResult> EditAsync(int id)
        {
            var TaskModel = await BussinesService.GetAsync(d => d.Id == id, ["AssignedUsers", "AssignedUsers.User", "TaskFiles"]);
            if (TaskModel == null)
                return NotFound();
            var viewModel = _mapper.Map<TaskModelFormViewModel>(TaskModel);
            viewModel.SelectedUsers = TaskModel.AssignedUsers.Select(x => x.UserId).ToList();
            viewModel.ExistingFiles = _mapper.Map<List<TaskFileDisplay>>(TaskModel.TaskFiles);
            return View("Form", PopulateViewModel(viewModel));
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Roles = AppRoles.Admin + "," + AppRoles.SuperAdmin)]
        public async Task<IActionResult> EditAsync(TaskModelFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var TaskModel = await BussinesService.GetAsync(d => d.Id == viewModel.Id, ["AssignedUsers", "Reminders", "AssignedUsers.User"]);
            if (TaskModel == null)
                return NotFound();
            _mapper.Map(viewModel, TaskModel);

            // Clear existing assigned users
            TaskModel.AssignedUsers.Clear();
            foreach (var userId in viewModel.SelectedUsers)
            {
                var user = await UserService.GetAsync(x => x.Id == userId);
                if (user != null)
                {
                    TaskModel.AssignedUsers.Add(new TaskUser
                    {
                        UserId = user.Id,
                        TaskModel = TaskModel
                    });
                }
            }


            #region Files List
            // Handle file uploads
            if (viewModel.TaskFiles.Any())
            {
                foreach (var file in viewModel.TaskFiles)
                {
                    if (file.Length > 0)
                    {

                        var fileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
                        var filePath = "/files/Tasks";
                        if (!Directory.Exists($"{_webHostEnvironment.WebRootPath}{filePath}"))
                            Directory.CreateDirectory($"{_webHostEnvironment.WebRootPath}{filePath}");

                        var path = Path.Combine($"{_webHostEnvironment.WebRootPath}{filePath}", fileName);

                        using var stream = System.IO.File.Create(path);
                        await file.CopyToAsync(stream);

                        var taskFile = new TaskFile
                        {
                            FileUrl = $"{filePath}/{fileName}",
                            FileName = file.FileName,
                            TaskModel = TaskModel
                        };
                        TaskModel.TaskFiles.Add(taskFile);
                    }
                }
            }

            // Handle image deletions
            var deletedImageUrls = viewModel.DeletedFileUrls?.Split(',') ?? Array.Empty<string>();
            foreach (var imageUrl in deletedImageUrls)
            {
                if (!string.IsNullOrEmpty(imageUrl))
                {
                    var file = await TaskFileService.GetAsync(r => r.FileUrl == imageUrl);
                    if (file != null)
                    {
                        await TaskFileService.DeleteAsync(file.Id);
                    }

                    var oldFilePath = Path.Combine(_webHostEnvironment.WebRootPath, imageUrl.TrimStart('/'));
                    if (System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                }
            }
            #endregion
            await BussinesService.UpdateAsync(TaskModel.Id, TaskModel);
            return RedirectToAction("Index", _mapper.Map<TaskModelViewModel>(TaskModel));
        }
        [Authorize(Roles = AppRoles.Admin + "," + AppRoles.SuperAdmin)]
        public async Task<IActionResult> Delete(int id)
        {
            var TaskModel = await BussinesService.GetAsync(d => d.Id == id, ["AssignedUsers", "TaskFiles", "Reminders", "Reminders.Notifications", "Reminders.TaskReminderFiles", "AssignedUsers.User"]);
            if (TaskModel == null)
                return NotFound();
            try
            {
                foreach (var item in TaskModel.TaskFiles.ToList())
                {
                    await TaskFileService.DeleteAsync(item.Id);
                }
                foreach (var TaskReminder in TaskModel.Reminders.ToList())
                {
                    if (TaskReminder.JobId != null)
                    {
                        BackgroundJob.Delete(TaskReminder.JobId);
                    }
                    TaskReminder.Notifications.Clear();
                    foreach (var item in TaskReminder.TaskReminderFiles.ToList())
                    {
                        await TaskReminderFileService.DeleteAsync(item.Id);
                    }
                    await TaskReminderService.DeleteAsync(TaskReminder.Id);
                }
               // TaskModel.AssignedUsers.Clear();
                await BussinesService.DeleteAsync(id);
            }
            catch (Exception)
            {
                throw;
            }
            return Ok();
        }
        public async Task<IActionResult> Complete(int id)
        {
            var currentUserId = GetAuthenticatedUser();
            if (string.IsNullOrEmpty(currentUserId))
                return Unauthorized();
            var user = await UserService.GetAsync(x => x.Id == currentUserId, ["Department"]);

StaffWork.Web/Views/TaskModel/Form.cshtml
@model TaskModelFormViewModel

@{
	ViewData["Title"] = "المهام";
	int i = 1;
}

<div class="card shadow-sm">
	<div class="card-header">
		<h3 class="card-title"> مهمه</h3>
	</div>
	<div class="card-body">
		<form method="post" asp-controller="TaskModel" enctype="multipart/form-data" id="Form">
			@if (Model.Id > 0)
			{
				<input type="hidden" asp-for="Id" />
			}
			<div class="row col-12">
				<div class="row col-6 mb-6">
					<!--begin::Label-->
					<label class="col-lg-4 col-form-label required fw-semibold fs-6" asp-for="Title"></label>
					<!--end::Label-->
					<div class="col-lg-8">
						<!--begin::Row-->
						<div class="row">
							<!--begin::Col-->
							<div class="col-lg-8 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
								<input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0" placeholder="اسم المهمه" asp-for="Title">
								<span asp-validation-for="Title" class="fv-plugins-message-container invalid-feedback"></span>
							</div>
							<!--end::Col-->
						</div>
						<!--end::Row-->
					</div>
					<!--end::Col-->
				</div>
				<div class="row col-6 mb-6">
					<!--begin::Label-->
					<label class="mb-5 col-lg-4 col-form-label required fw-semibold fs-6">الموظفين</label>
					<!--end::Label-->
					<!--begin::Col-->
					<div class="col-lg-8">
						<!--begin::Row-->
						<div class="row">
							<!--begin::Col-->
							<div class="fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
								<select aria-label="Select a Country" multiple data-control="select2" data-placeholder="الموظفين..." class="js-select2 form-select form-select-solid form-select-lg fw-semibold"
										asp-for="SelectedUsers" asp-items="Model.Users">
									<option value="">الموظفين...</option>
								</select>
								<span asp-validation-for="SelectedUsers" class="text-danger d-block"></span>
							</div>
							<!--end::Col-->
						</div>
						<!--end::Row-->
					</div>
					<!--end::Col-->
				</div>
			</div>
			<div class="row">
				<!--begin::Label-->
				<label class="mb-5 col-lg-4 col-form-label fw-semibold fs-6" asp-for="Notes"></label>
				<!--end::Label-->
				<!--begin::Col-->
				<div class="col-lg-8">
					<!--begin::Row-->
					<div class="row">
						<!--begin::Col-->
						<div class="col-lg-12 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
							<textarea class="form-control form-control-solid" type="text" placeholder="اكتب ملاحظاتك" asp-for="Notes"></textarea>
							<span asp-validation-for="Notes" class="fv-plugins-message-container invalid-feedback"></span>
							<!--end::Col-->
						</div>
					</div>
					<!--end::Row-->
				</div>
				<!--end::Col-->
			</div>
			@if (Model.Id > 0)
			{
				<div class="row">
					<!--begin::Label-->
					<label class="col-lg-4 col-form-label fw-semibold fs-6">ملف المهمه</label>
					<!--end::Label-->
					<!--begin::Col-->
					<div id="head" class="col-lg-8">
						@if (Model.ExistingFiles != null && Model.ExistingFiles.Any())
						{
							<div class="mb-3 col-lg-12">
								<!-- Display each existing image with a download link and name -->
								@foreach (var item in Model.ExistingFiles)
								{
									<div class="image-item" id="image-item-@i">
										<h3 class="fw-bold" title="@item.FileName" data-toggle="tooltip" data-placement="top">
											@((item.FileName?.Length > 60 ? item.FileName.Substring(0, 60) + "..." : item.FileName))
										</h3>
										<a href="@item.FileUrl" class="btn btn-primary mb-2" target="_blank">تحميل الملف @i</a>
										<button type="button" class="btn btn-sm btn-danger" onclick="deleteImage('@item.FileUrl', '@i')">حذف</button>
									</div>
									i++;
								}
							</div>
						}
					</div>
					<!--end::Col-->
				</div>
			}
			else
			{
				<!--begin::Row-->
				<div class="row">
					<!--begin::Label-->
					<label class="col-lg-4 col-form-label fw-semibold fs-6" asp-for="TaskFiles"></label>
					<!--end::Label-->
					<!--begin::Col-->
					<div id="head" class="mb-5 col-lg-8 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
					</div>
					<!--end::Col-->
				</div>
				<!--end::Row-->
			}
			<!-- Button to add more file inputs -->
			<button type="button" class="btn btn-info mb-2" onclick="addFileInput()">اضافه ملف</button>
			<!-- Hidden input to track deleted image URLs -->
			<input type="hidden" name="DeletedFileUrls" id="DeletedFileUrls" value="" />

		</form>

	</div>
	<div class="card-footer">
		<button type="submit" class="btn btn-primary" form="Form">
			<span class="indicator-label">
				حفظ
			</span>
			<span class="indicator-progress">
				رجاء الانتظار... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
			</span>
		</button>
		<a class="btn btn-light text-primary ms-3" asp-action="Index">Cancel</a>
	</div>
</div>


@section Scripts
{
	<partial name="_ValidationScriptsPartial" />

	<script>
		$('.js-select2').select2({
						dir: "rtl", // الاتجاه من اليمين لليسار
						width: '100%',
						placeholder: "الموظفين..."
					});

		// Function to dynamically add new file input to the 'head' container
		function addFileInput() {
			// Get the 'head' container
			var container = document.getElementById('head');

			// Create a new div to hold the input and label
			var inputBlock = document.createElement('div');
			inputBlock.classList.add('mb-3');

			// Create label for new file input
			var label = document.createElement('label');
			label.classList.add('form-label');
			label.innerText = 'اختر ملف جديد:';

			// Create the new file input element
			var input = document.createElement('input');
			input.type = 'file';
			input.name = 'TaskFiles';
			input.classList.add('form-control');
			input.multiple = true;

			// Create a span for validation messages (if any)
			var validationSpan = document.createElement('span');
			validationSpan.classList.add('text-danger');

			// Append the label, input, and validation span to the input block
			inputBlock.appendChild(label);
			inputBlock.appendChild(input);
			inputBlock.appendChild(validationSpan);

			// Append the new input block to the 'head' container
			container.appendChild(inputBlock);
		}

		// Function to delete an image and remove it from the UI
		function deleteImage(imageUrl, imageIndex) {
			if (confirm('Are you sure you want to delete this image?')) {
				// Track deleted images in hidden field
				const deletedImagesInput = document.getElementById('DeletedFileUrls');
				let deletedFileUrls = deletedImagesInput.value ? deletedImagesInput.value.split(',') : [];
				deletedFileUrls.push(imageUrl);
				deletedImagesInput.value = deletedFileUrls.join(',');

				// Remove the image's UI element
				var imageItem = document.getElementById('image-item-' + imageIndex);
				if (imageItem) {
					imageItem.remove();
				}
			}
		}
	</script>
}

StaffWork.Web/Views/TaskModel/Index.cshtml
@using StaffWork.Core.Consts
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery

@{
	ViewData["Title"] = "المهام";
	var isSuperAdminOrAdmin = User.IsInRole(AppRoles.SuperAdmin) || User.IsInRole(AppRoles.Admin);
}

@section Styles
{
	<link rel="stylesheet" href="~/assets/plugins/datatables/datatables.bundle.css" />
}


<div class="card shadow-sm">
	<div class="card-header align-items-center py-5 gap-2 gap-md-5">
		<div class="card-title">
			<div class="d-flex align-items-center position-relative my-1">
				<span class="svg-icon svg-icon-1 position-absolute ms-4">
					<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
						<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
						<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
					</svg>
				</span>
				<input type="text" data-kt-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="بحث..." />
			</div>
			<div id="kt_datatable_example_1_export" class="d-none"></div>
		</div>
		@if (isSuperAdminOrAdmin)
		{
			<div class="card-toolbar flex-row-fluid justify-content-end gap-5">
				<a asp-controller="TaskModel" asp-action="Create" class="btn btn-light-primary">
					<i class="bi bi-plus-square-dotted"></i>
					اضافه مهمه
				</a>
			</div>
		}
		<div class="card-toolbar flex-row-fluid justify-content-end gap-5">
			<a href="javascript:void(0);" class="btn btn-light-primary" onclick="exportToExcel()">
				<span class="svg-icon svg-icon-2">
					<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
						<rect opacity="0.3" width="12" height="2" rx="1" transform="matrix(0 -1 -1 0 12.75 19.75)" fill="currentColor"></rect>
						<path d="M12.0573 17.8813L13.5203 16.1256C13.9121 15.6554 14.6232 15.6232 15.056 16.056C15.4457 16.4457 15.4641 17.0716 15.0979 17.4836L12.4974 20.4092C12.0996 20.8567 11.4004 20.8567 11.0026 20.4092L8.40206 17.4836C8.0359 17.0716 8.0543 16.4457 8.44401 16.056C8.87683 15.6232 9.58785 15.6554 9.9797 16.1256L11.4427 17.8813C11.6026 18.0732 11.8974 18.0732 12.0573 17.8813Z" fill="currentColor"></path>
						<path opacity="0.3" d="M18.75 15.75H17.75C17.1977 15.75 16.75 15.3023 16.75 14.75C16.75 14.1977 17.1977 13.75 17.75 13.75C18.3023 13.75 18.75 13.3023 18.75 12.75V5.75C18.75 5.19771 18.3023 4.75 17.75 4.75L5.75 4.75C5.19772 4.75 4.75 5.19771 4.75 5.75V12.75C4.75 13.3023 5.19771 13.75 5.75 13.75C6.30229 13.75 6.75 14.1977 6.75 14.75C6.75 15.3023 6.30229 15.75 5.75 15.75H4.75C3.64543 15.75 2.75 14.8546 2.75 13.75V4.75C2.75 3.64543 3.64543 2.75 4.75 2.75L18.75 2.75C19.8546 2.75 20.75 3.64543 20.75 4.75V13.75C20.75 14.8546 19.8546 15.75 18.75 15.75Z" fill="currentColor"></path>
					</svg>
				</span>
				تصدير كملف excel
			</a>
		</div>

		@* <div class="d-flex col-12 justify-content-between">
			<div class="d-flex">
				<span class="input-group-text" style="margin-left:10px">من تاريخ</span>
				<input type="date" id="fromDate" class="form-control form-control-solid" placeholder="من تاريخ" />
			</div>
			<div class="d-flex">
				<span class="input-group-text" style="margin-left:10px">إلى تاريخ</span>
				<input type="date" id="toDate" class="form-control form-control-solid" placeholder="إلى تاريخ" />
			</div>
			<div>
				<button type="button" id="searchButton" class="btn btn-primary">بحث</button>
				<button type="button" id="deleteSearch" class="btn btn-secondary" onclick="location.reload()">حذف البحث</button>
			</div>
		</div> *@
	</div>
	<div class="card-body fs-5 pt-0">
		<div class="table-responsive">
			<table id="TaskModels" class="text-center fs-4 table table-row-dashed table-row-gray-300 gy-5">
				<thead>
					<tr class="fw-bold text-gray-800">
						<th class="d-none"></th>
						<th>اسم المهمه</th>
						<th>الموظفين</th>
						<th>حاله الاستلام</th>
						<th>تاريخ الاستلام</th>
						<th>حاله الانجاز</th>
						<th>تاريخ الانجاز</th>
						<th>ملاحظه</th>
						@if (!isSuperAdminOrAdmin)
						{
							<th>استلام</th>
							<th>انجاز</th>
						}
						<th class="text-start">تفاصيل</th>
						@if (isSuperAdminOrAdmin)
						{
							<th class="text-start">تعديل</th>
							<th class="text-start">حذف</th>
						}
					</tr>
				</thead>
				<tbody data-url="/TaskModel/GetTaskModels" data-controller="TaskModel">
					@* TaskModels will be rendered here *@
				</tbody>
			</table>
		</div>
	</div>
</div>

<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />


@section Plugins
{
	<script src="~/assets/plugins/datatables/datatables.bundle.js"></script>
}
@section Scripts
{
	<script src="~/js/TaskModel.js" asp-append-version="true"></script>
	<script type="text/javascript">
		var isSuperAdminOrAdmin = @isSuperAdminOrAdmin.ToString().ToLower();
	</script>
	<script>
		$('#searchButton').on('click', function () {
			var fromDate = $('#fromDate').val();
			var toDate = $('#toDate').val();

			// Update DataTable AJAX URL with date filters
			datatable.ajax.url('/TaskModel/GetTaskModels?fromDate=' + encodeURIComponent(fromDate) + '&toDate=' + encodeURIComponent(toDate)).load();
		});


		function exportToExcel() {
			// Get the DataTable instance
			var table = $('#TaskModels').DataTable();

			// Get the current search value
			var searchValue = table.search();

			// Get the current sorting column and direction
			var order = table.order();
			var sortColumnIndex = order[0][0]; // Get the index of the sorted column
			var sortColumnDirection = order[0][1]; // asc or desc

			// Get the column name for sorting
			var sortColumn = table.settings().init().columns[sortColumnIndex].name;

			// Get the filter values if needed (for example, date filters)
			var fromDate = $('#fromDateInput').val();
			var toDate = $('#toDateInput').val();

			// Construct the export URL with the search and sort parameters
			var url = `/TaskModel/ExportToExcel?searchValue=${encodeURIComponent(searchValue)}&sortColumn=${sortColumn}&sortColumnDirection=${sortColumnDirection}&fromDate=${fromDate}&toDate=${toDate}`;

			// Redirect to the generated URL to download the Excel file
			window.location.href = url;
		}

	</script>
}