StaffWork.Web/Controllers/WorkTypeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using StaffWork.Api.Controllers;
using StaffWork.Core.Interfaces;
using StaffWork.Core.Models;
using StaffWork.Core.Paramaters;
using StaffWork.Infrastructure.Filters;

namespace StaffWork.Web.Controllers
{
    public class WorkTypeController : ApiBaseController<WorkType>
    {
        public WorkTypeController(IServicesBase<WorkType> servicesBase, IMapper mapper) : base(servicesBase, mapper)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await BussinesService.GetAllAsync();
            var viewModel = _mapper.Map<IEnumerable<WorkTypeViewModel>>(model);

            var model1 = new Tuple<IEnumerable<WorkTypeViewModel>, WorkTypeViewModel>(
                            viewModel, new WorkTypeViewModel());

            return View(model1);
        }
        [HttpPost]
        public async Task<IActionResult> Create(WorkTypeViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var WorkType = _mapper.Map<WorkType>(viewModel);
            await BussinesService.InsertAsync(WorkType);
            return RedirectToAction("Index", _mapper.Map<WorkTypeViewModel>(WorkType));
        }
        [HttpGet]
        [AjaxOnly]
        public async Task<IActionResult> EditAsync(int id)
        {
            var WorkType = await BussinesService.GetAsync(d => d.Id == id);
            if (WorkType == null)
                return NotFound();
            var viewModel = _mapper.Map<WorkTypeViewModel>(WorkType);
            return PartialView("_FormEdit", viewModel);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditAsync(WorkTypeViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var WorkType = await BussinesService.GetAsync(d => d.Id == viewModel.Id);
            if (WorkType == null)
                return NotFound();
            _mapper.Map(viewModel, WorkType);

            await BussinesService.UpdateAsync(WorkType.Id, WorkType);
            return RedirectToAction("Index", _mapper.Map<WorkTypeViewModel>(WorkType));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var WorkType = await BussinesService.GetAsync(d => d.Id == id);
            if (WorkType == null)
                return NotFound();
            try
            {
                await BussinesService.DeleteAsync(id);
            }
            catch (Exception)
            {
                throw;
            }
            return Ok();
        }
        public async Task<IActionResult> AllowItem(WorkTypeViewModel model)
        {
            var WorkType = await BussinesService.GetAsync(d => d.Name == model.Name);

            var isAllowed = WorkType is null || WorkType.Id.Equals(model.Id);

            return Json(isAllowed);
        }
    }
}

StaffWork.Web/Views/WorkType/Index.cshtml
@model Tuple<IEnumerable<WorkTypeViewModel>, WorkTypeViewModel>
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery

@{
    ViewData["Title"] = "الاعمال المتاحه";
}
@section Styles
{
    <link rel="stylesheet" href="~/assets/plugins/datatables/datatables.bundle.css" />
}
<partial name="_Form" model="@Model.Item2" />
<div class="card shadow-sm">
    <partial name="_DataTablesCardHeader" />
    <div class="card-body pt-0">
        <div class="table-responsive">
            <table class="table table-row-dashed fs-2 gy-7 js-datatables" data-document-title="WorkTypes">
                <thead>
                    <tr class="fw-bold">
                        <th style="text-align:start">العمل</th>
                        <th class="js-no-export" style="text-align:center">تعديل</th>
                        <th class="js-no-export" style="text-align:end">حذف</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var type in @Model.Item1)
                    {
                        <partial name="_WorkTypeRow" model="@type" />
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />

@section Plugins
{
    <script src="~/assets/plugins/datatables/datatables.bundle.js"></script>
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

StaffWork.Web/Views/WorkType/_Form.cshtml
@model WorkTypeViewModel

<div class="alert bg-light-primary border border-primary border-3 border-dashed d-flex justify-content-between w-100 p-5 mb-10">
    <form method="post" asp-controller="WorkType" class="w-50" enctype="multipart/form-data" id="Form">
        <div class="d-flex align-items-center w-100 me-20">
            <div class="row w-100">
                <!--begin::Label-->
                <label class="col-lg-4 col-form-label fs-2" asp-for="Name">أسم العمل</label>
                <!--end::Label-->
                <!--begin::Col-->
                <div class="col-lg-8">
                    <!--begin::Row-->
                    <div class="row">
                        <!--begin::Col-->
                        <div class="col-lg-12 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
                            <input class="form-control form-control-solid fs-2" type="text" placeholder="ادحل أسم العمل" asp-for="Name" />
                            <span asp-validation-for="Name" class="fv-plugins-message-container invalid-feedback"></span>
                            <!--end::Col-->
                        </div>
                    </div>
                    <!--end::Row-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Content-->
        </div>
    </form>
    <div class=" align-content-center">
        <button type="submit" asp-controller="WorkType" asp-action="Create" class="btn btn-sm btn-primary" form="Form">
            <i class="bi bi-plus-square-dotted"></i>
            اضافه
        </button>
    </div>
</div>

StaffWork.Web/Views/WorkType/_FormEdit.cshtml
@model WorkTypeViewModel

<form asp-action="@(Model?.Id > 0 ? "Edit" : "Create")"
      data-ajax-method="post"
      data-ajax="true"
      data-ajax-begin="onModalBegin"
      data-ajax-success="onModalSuccess"
      data-ajax-failure="showErrorMessage"
      data-ajax-complete="onModalComplete">
    @if (Model?.Id > 0)
    {
        <input type="hidden" asp-for="Id" />
    }
    <div class="row mb-6">
        <!--begin::Label-->
        <label class="col-lg-4 col-form-label required fw-semibold fs-4" asp-for="Name"></label>
        <!--end::Label-->
        <!--begin::Col-->
        <div class="col-lg-12">
            <!--begin::Row-->
            <div class="row">
                <!--begin::Col-->
                <div class="col-lg-12 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-invalid">
                    <input type="text" class="form-control form-control-lg form-control-solid mb-3 mb-lg-0 fs-4" asp-for="Name">
                    <span asp-validation-for="Name" class="fv-plugins-message-container invalid-feedback fs-6"></span>
                </div>
                <!--end::Col-->
            </div>
            <!--end::Row-->
        </div>
        <!--end::Col-->
    </div>
    <partial name="_ModalFooter" />
</form>

StaffWork.Web/Views/WorkType/_WorkTypeRow.cshtml
@model WorkTypeViewModel
<tr>
    <td>@Model.Name</td>
    <td style="text-align:center">
        <a href="javascript:;" class="btn btn-sm btn-outline btn-outline-dashed btn-outline-primary btn-active-light-primary js-render-modal"
           data-title="تعديل العمل" data-url="/WorkType/Edit/@Model.Id" data-update="true">
            تعديل العمل
        </a>
    </td>
    <td style="text-align:end">
        <a href="javascript:;" class="btn btn-sm btn-outline btn-outline-dashed btn-outline-danger btn-active-light-danger js-confirm"
           data-title="حذف العمل" data-url="/WorkType/Delete/@Model.Id" data-update="true" data-message="هل متأكد من حذف هذا العمل؟">
            حذف العمل
        </a>
    </td>
</tr>